// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountRestrictionDTO } from './account-restriction-dto';

/**
 * 
 * @export
 * @interface AccountRestrictionsDTO
 */
export interface AccountRestrictionsDTO {
    /**
     * The address of the account in hexadecimal.
     * @type {string}
     * @memberof AccountRestrictionsDTO
     */
    address: string;
    /**
     * 
     * @type {Array<AccountRestrictionDTO>}
     * @memberof AccountRestrictionsDTO
     */
    restrictions: Array<AccountRestrictionDTO>;
}


