// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The account restriction type: * 0x01 (1 decimal) - Allow only receiving transactions from an address. * 0x02 (2 decimal) - Allow only receiving transactions containing a mosaic id. * 0x04 (4 decimal) - Allow only sending transactions with a given transaction type. * 0x05 (5 decimal) - Restriction type sentinel. * 0x81 (129 decimal) - Block receiving transactions from an address. * 0x82 (130 decimal) - Block receiving transactions containing a mosaic id. * 0x84 (132 decimal) -  Block sending transactions with a given transaction type. 
 * @export
 * @enum {string}
 */
export enum AccountRestrictionTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_129 = 129,
    NUMBER_130 = 130,
    NUMBER_132 = 132
}



