// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountMetaDTO
 */
export interface AccountMetaDTO {
    /**
     * 
     * @type {Array<number>}
     * @memberof AccountMetaDTO
     */
    height: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof AccountMetaDTO
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof AccountMetaDTO
     */
    merkleComponentHash: string;
    /**
     * 
     * @type {number}
     * @memberof AccountMetaDTO
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof AccountMetaDTO
     */
    id: string;
}


