// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountDTO } from './account-dto';
import { AccountMetaDTO } from './account-meta-dto';

/**
 * 
 * @export
 * @interface AccountInfoDTO
 */
export interface AccountInfoDTO {
    /**
     * 
     * @type {AccountMetaDTO}
     * @memberof AccountInfoDTO
     */
    meta: AccountMetaDTO;
    /**
     * 
     * @type {AccountDTO}
     * @memberof AccountInfoDTO
     */
    account: AccountDTO;
}


