// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MosaicDTO } from './mosaic-dto';

/**
 * 
 * @export
 * @interface AccountDTO
 */
export interface AccountDTO {
    /**
     * The account unique address in hexadecimal. 
     * @type {string}
     * @memberof AccountDTO
     */
    address: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof AccountDTO
     */
    addressHeight: Array<number>;
    /**
     * The public key of an account can be used to verify signatures of the account. Only accounts that have already published a transaction have a public key assigned to the account. Otherwise, the field is null. 
     * @type {string}
     * @memberof AccountDTO
     */
    publicKey: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof AccountDTO
     */
    publicKeyHeight: Array<number>;
    /**
     * The list of mosaics the account owns. The amount is represented in absolute amount. Thus a balance of 123456789 for a mosaic with divisibility 6 (absolute) means the account owns 123.456789 instead. 
     * @type {Array<MosaicDTO>}
     * @memberof AccountDTO
     */
    mosaics: Array<MosaicDTO>;
    /**
     * 
     * @type {Array<number>}
     * @memberof AccountDTO
     */
    importance: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof AccountDTO
     */
    importanceHeight: Array<number>;
}


