// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountRestrictionTypeEnum } from './account-restriction-type-enum';

/**
 * 
 * @export
 * @interface AccountRestrictionDTO
 */
export interface AccountRestrictionDTO {
    /**
     * 
     * @type {AccountRestrictionTypeEnum}
     * @memberof AccountRestrictionDTO
     */
    restrictionType: AccountRestrictionTypeEnum;
    /**
     * The address, transaction type or mosaic id to restrict.
     * @type {Array<object>}
     * @memberof AccountRestrictionDTO
     */
    values: Array<object>;
}


