// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlockMetaDTO
 */
export interface BlockMetaDTO {
    /**
     * 
     * @type {string}
     * @memberof BlockMetaDTO
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof BlockMetaDTO
     */
    generationHash: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BlockMetaDTO
     */
    subCacheMerkleRoots: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BlockMetaDTO
     */
    totalFee: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof BlockMetaDTO
     */
    numTransactions: number;
    /**
     * 
     * @type {number}
     * @memberof BlockMetaDTO
     */
    numStatements?: number;
}


