// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MosaicPropertyDTO } from './mosaic-property-dto';

/**
 * 
 * @export
 * @interface MosaicDefinitionDTO
 */
export interface MosaicDefinitionDTO {
    /**
     * 
     * @type {Array<number>}
     * @memberof MosaicDefinitionDTO
     */
    mosaicId: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof MosaicDefinitionDTO
     */
    supply: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof MosaicDefinitionDTO
     */
    height: Array<number>;
    /**
     * The public key of the mosaic owner.
     * @type {string}
     * @memberof MosaicDefinitionDTO
     */
    owner: string;
    /**
     * The number of definitions for the same mosaic.
     * @type {number}
     * @memberof MosaicDefinitionDTO
     */
    revision: number;
    /**
     * 
     * @type {Array<MosaicPropertyDTO>}
     * @memberof MosaicDefinitionDTO
     */
    properties: Array<MosaicPropertyDTO>;
}


