// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MosaicDefinitionDTO } from './mosaic-definition-dto';
import { MosaicMetaDTO } from './mosaic-meta-dto';

/**
 * 
 * @export
 * @interface MosaicInfoDTO
 */
export interface MosaicInfoDTO {
    /**
     * 
     * @type {MosaicMetaDTO}
     * @memberof MosaicInfoDTO
     */
    meta: MosaicMetaDTO;
    /**
     * 
     * @type {MosaicDefinitionDTO}
     * @memberof MosaicInfoDTO
     */
    mosaic: MosaicDefinitionDTO;
}


