// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of the modification: * 0 - Add cosignatory. * 1 - Remove cosignatory. 
 * @export
 * @enum {string}
 */
export enum MultisigModificationTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}



