// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MultisigDTO
 */
export interface MultisigDTO {
    /**
     * The account public key.
     * @type {string}
     * @memberof MultisigDTO
     */
    account: string;
    /**
     * The account address in hexadecimal.
     * @type {string}
     * @memberof MultisigDTO
     */
    accountAddress?: string;
    /**
     * The number of signatures needed to approve a transaction.
     * @type {number}
     * @memberof MultisigDTO
     */
    minApproval: number;
    /**
     * The number of signatures needed to remove a cosignatory.
     * @type {number}
     * @memberof MultisigDTO
     */
    minRemoval: number;
    /**
     * The array of public keys of the cosignatory accounts.
     * @type {Array<string>}
     * @memberof MultisigDTO
     */
    cosignatories: Array<string>;
    /**
     * The array of multisig accounts where the account is cosignatory.
     * @type {Array<string>}
     * @memberof MultisigDTO
     */
    multisigAccounts: Array<string>;
}


