// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MultisigAccountInfoDTO } from './multisig-account-info-dto';

/**
 * 
 * @export
 * @interface MultisigAccountGraphInfoDTO
 */
export interface MultisigAccountGraphInfoDTO {
    /**
     * The level of the multisig account.
     * @type {number}
     * @memberof MultisigAccountGraphInfoDTO
     */
    level: number;
    /**
     * The array of multisig accounts for this level.
     * @type {Array<MultisigAccountInfoDTO>}
     * @memberof MultisigAccountGraphInfoDTO
     */
    multisigEntries: Array<MultisigAccountInfoDTO>;
}


