// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NamespaceNameDTO
 */
export interface NamespaceNameDTO {
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceNameDTO
     */
    parentId?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceNameDTO
     */
    namespaceId: Array<number>;
    /**
     * The name of the namespace.
     * @type {string}
     * @memberof NamespaceNameDTO
     */
    name: string;
}


