// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NamespaceMetaDTO
 */
export interface NamespaceMetaDTO {
    /**
     * 
     * @type {string}
     * @memberof NamespaceMetaDTO
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof NamespaceMetaDTO
     */
    active: boolean;
    /**
     * 
     * @type {number}
     * @memberof NamespaceMetaDTO
     */
    index: number;
}


