// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AliasDTO } from './alias-dto';
import { NamespaceTypeEnum } from './namespace-type-enum';

/**
 * 
 * @export
 * @interface NamespaceDTO
 */
export interface NamespaceDTO {
    /**
     * The public key of the owner of the namespace.
     * @type {string}
     * @memberof NamespaceDTO
     */
    owner: string;
    /**
     * The address of the owner of the namespace in hexadecimal.
     * @type {string}
     * @memberof NamespaceDTO
     */
    ownerAddress: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    startHeight: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    endHeight: Array<number>;
    /**
     * The level of the namespace.
     * @type {number}
     * @memberof NamespaceDTO
     */
    depth: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    level0: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    level1?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    level2?: Array<number>;
    /**
     * 
     * @type {NamespaceTypeEnum}
     * @memberof NamespaceDTO
     */
    type: NamespaceTypeEnum;
    /**
     * 
     * @type {AliasDTO}
     * @memberof NamespaceDTO
     */
    alias: AliasDTO;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    parentId: Array<number>;
}


