// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of the receipt: * 0x134D (4941 decimal) - Mosaic_Rental_Fee. * 0x124E (4686 decimal) - Namespace_Rental_Fee. * 0x2143 (8515 decimal) - Harvest_Fee. * 0x2248 (8776 decimal) - LockHash_Completed. * 0x2348 (9032 decimal) - LockHash_Expired. * 0x2252 (8786 decimal) - LockSecret_Completed. * 0x2352 (9042 decimal) - LockSecret_Expired. * 0x3148 (12616 decimal) - LockHash_Created. * 0x3152 (12626 decimal) - LockSecret_Created. * 0x414D (16717 decimal) - Mosaic_Expired. * 0x414E (16718 decimal) - Namespace_Expired. * 0x5143 (20803 decimal) - Inflation. * 0xE134 (57652 decimal) - Transaction_Group. * 0xF143 (61763 decimal) - Address_Alias_Resolution. * 0xF243 (62019 decimal) - Mosaic_Alias_Resolution. 
 * @export
 * @enum {string}
 */
export enum ReceiptTypeEnum {
    NUMBER_4685 = 4685,
    NUMBER_4941 = 4941,
    NUMBER_4686 = 4686,
    NUMBER_8515 = 8515,
    NUMBER_8776 = 8776,
    NUMBER_9042 = 9042,
    NUMBER_12616 = 12616,
    NUMBER_12626 = 12626,
    NUMBER_16717 = 16717,
    NUMBER_16718 = 16718,
    NUMBER_20803 = 20803,
    NUMBER_57652 = 57652,
    NUMBER_61763 = 61763,
    NUMBER_62019 = 62019
}



