// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ResolutionEntryDTO } from './resolution-entry-dto';

/**
 * A resolution statement keeps the relation between a namespace alias used in a transaction and the real address or mosaicId.
 * @export
 * @interface ResolutionStatementDTO
 */
export interface ResolutionStatementDTO {
    /**
     * 
     * @type {Array<number>}
     * @memberof ResolutionStatementDTO
     */
    height: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ResolutionStatementDTO
     */
    unresolved: Array<number>;
    /**
     * The array of resolution entries linked to the unresolved namespaceId. It is an array instead of a single UInt64 field since within one block the resolution might change for different sources due to alias related transactions.
     * @type {Array<ResolutionEntryDTO>}
     * @memberof ResolutionStatementDTO
     */
    resolutionEntries: Array<ResolutionEntryDTO>;
}


