// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The role of the node: * 1 - A peer node. * 2 - An api node. 
 * @export
 * @enum {string}
 */
export enum RolesTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}



