// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ResolutionStatementDTO } from './resolution-statement-dto';
import { TransactionStatementDTO } from './transaction-statement-dto';

/**
 * The collection of transaction statements and resolutions triggered for the block requested.
 * @export
 * @interface StatementsDTO
 */
export interface StatementsDTO {
    /**
     * The array of transaction statements for the block requested.
     * @type {Array<TransactionStatementDTO>}
     * @memberof StatementsDTO
     */
    transactionStatements: Array<TransactionStatementDTO>;
    /**
     * The array of address resolutions for the block requested.
     * @type {Array<ResolutionStatementDTO>}
     * @memberof StatementsDTO
     */
    addressResolutionStatements: Array<ResolutionStatementDTO>;
    /**
     * The array of mosaic resolutions for the block requested.
     * @type {Array<ResolutionStatementDTO>}
     * @memberof StatementsDTO
     */
    mosaicResolutionStatements: Array<ResolutionStatementDTO>;
}


