// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StorageInfoDTO
 */
export interface StorageInfoDTO {
    /**
     * The number of blocks stored.
     * @type {number}
     * @memberof StorageInfoDTO
     */
    numBlocks: number;
    /**
     * The number of transactions stored.
     * @type {number}
     * @memberof StorageInfoDTO
     */
    numTransactions: number;
    /**
     * The number of accounts created.
     * @type {number}
     * @memberof StorageInfoDTO
     */
    numAccounts: number;
}


