// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SourceDTO } from './source-dto';

/**
 * The collection of receipts related to a transaction.
 * @export
 * @interface TransactionStatementDTO
 */
export interface TransactionStatementDTO {
    /**
     * 
     * @type {Array<number>}
     * @memberof TransactionStatementDTO
     */
    height: Array<number>;
    /**
     * 
     * @type {SourceDTO}
     * @memberof TransactionStatementDTO
     */
    source: SourceDTO;
    /**
     * The array of receipts.
     * @type {Array<object>}
     * @memberof TransactionStatementDTO
     */
    receipts: Array<object>;
}


