// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionStatusDTO
 */
export interface TransactionStatusDTO {
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusDTO
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusDTO
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusDTO
     */
    hash?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof TransactionStatusDTO
     */
    deadline?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof TransactionStatusDTO
     */
    height?: Array<number>;
}


