// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';

import { BlockchainScoreDTO } from '../model';
import { HeightInfoDTO } from '../model';
/**
 * ChainRoutesApi - axios parameter creator
 * @export
 */
export const ChainRoutesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the current height of the blockchain.
         * @summary Get the current height of the chain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBlockchainHeight(options: any = {}): RequestArgs {
            const localVarPath = `/chain/height`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the current score of the blockchain. The higher the score, the better the chain. During synchronization, nodes try to get the best blockchain in the network.  The score for a block is derived from its difficulty and the time (in seconds) that has elapsed since the last block:      block score = difficulty − time elapsed since last block 
         * @summary Get the current score of the chain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBlockchainScore(options: any = {}): RequestArgs {
            const localVarPath = `/chain/score`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChainRoutesApi - functional programming interface
 * @export
 */
export const ChainRoutesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Returns the current height of the blockchain.
         * @summary Get the current height of the chain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBlockchainHeight(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<HeightInfoDTO> {
            const localVarAxiosArgs = ChainRoutesApiAxiosParamCreator(configuration).getBlockchainHeight(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets the current score of the blockchain. The higher the score, the better the chain. During synchronization, nodes try to get the best blockchain in the network.  The score for a block is derived from its difficulty and the time (in seconds) that has elapsed since the last block:      block score = difficulty − time elapsed since last block 
         * @summary Get the current score of the chain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBlockchainScore(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockchainScoreDTO> {
            const localVarAxiosArgs = ChainRoutesApiAxiosParamCreator(configuration).getBlockchainScore(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ChainRoutesApi - factory interface
 * @export
 */
export const ChainRoutesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Returns the current height of the blockchain.
         * @summary Get the current height of the chain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBlockchainHeight(options?: any) {
            return ChainRoutesApiFp(configuration).getBlockchainHeight(options)(axios, basePath);
        },
        /**
         * Gets the current score of the blockchain. The higher the score, the better the chain. During synchronization, nodes try to get the best blockchain in the network.  The score for a block is derived from its difficulty and the time (in seconds) that has elapsed since the last block:      block score = difficulty − time elapsed since last block 
         * @summary Get the current score of the chain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBlockchainScore(options?: any) {
            return ChainRoutesApiFp(configuration).getBlockchainScore(options)(axios, basePath);
        },
    };
};

/**
 * ChainRoutesApi - object-oriented interface
 * @export
 * @class ChainRoutesApi
 * @extends {BaseAPI}
 */
export class ChainRoutesApi extends BaseAPI {
    /**
     * Returns the current height of the blockchain.
     * @summary Get the current height of the chain
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChainRoutesApi
     */
    public getBlockchainHeight(options?: any) {
        return ChainRoutesApiFp(this.configuration).getBlockchainHeight(options)(this.axios, this.basePath);
    }

    /**
     * Gets the current score of the blockchain. The higher the score, the better the chain. During synchronization, nodes try to get the best blockchain in the network.  The score for a block is derived from its difficulty and the time (in seconds) that has elapsed since the last block:      block score = difficulty − time elapsed since last block 
     * @summary Get the current score of the chain
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChainRoutesApi
     */
    public getBlockchainScore(options?: any) {
        return ChainRoutesApiFp(this.configuration).getBlockchainScore(options)(this.axios, this.basePath);
    }

}
