// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';

import { ServerDTO } from '../model';
import { StorageInfoDTO } from '../model';
/**
 * DiagnosticRoutesApi - axios parameter creator
 * @export
 */
export const DiagnosticRoutesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns diagnostic information about the node storage.
         * @summary Get the storage information of the node
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDiagnosticStorage(options: any = {}): RequestArgs {
            const localVarPath = `/diagnostic/storage`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the version of the running rest component.
         * @summary Get the version of the running rest component
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServerInfo(options: any = {}): RequestArgs {
            const localVarPath = `/diagnostic/server`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DiagnosticRoutesApi - functional programming interface
 * @export
 */
export const DiagnosticRoutesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Returns diagnostic information about the node storage.
         * @summary Get the storage information of the node
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDiagnosticStorage(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<StorageInfoDTO> {
            const localVarAxiosArgs = DiagnosticRoutesApiAxiosParamCreator(configuration).getDiagnosticStorage(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Returns the version of the running rest component.
         * @summary Get the version of the running rest component
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServerInfo(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServerDTO> {
            const localVarAxiosArgs = DiagnosticRoutesApiAxiosParamCreator(configuration).getServerInfo(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DiagnosticRoutesApi - factory interface
 * @export
 */
export const DiagnosticRoutesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Returns diagnostic information about the node storage.
         * @summary Get the storage information of the node
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDiagnosticStorage(options?: any) {
            return DiagnosticRoutesApiFp(configuration).getDiagnosticStorage(options)(axios, basePath);
        },
        /**
         * Returns the version of the running rest component.
         * @summary Get the version of the running rest component
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServerInfo(options?: any) {
            return DiagnosticRoutesApiFp(configuration).getServerInfo(options)(axios, basePath);
        },
    };
};

/**
 * DiagnosticRoutesApi - object-oriented interface
 * @export
 * @class DiagnosticRoutesApi
 * @extends {BaseAPI}
 */
export class DiagnosticRoutesApi extends BaseAPI {
    /**
     * Returns diagnostic information about the node storage.
     * @summary Get the storage information of the node
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiagnosticRoutesApi
     */
    public getDiagnosticStorage(options?: any) {
        return DiagnosticRoutesApiFp(this.configuration).getDiagnosticStorage(options)(this.axios, this.basePath);
    }

    /**
     * Returns the version of the running rest component.
     * @summary Get the version of the running rest component
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiagnosticRoutesApi
     */
    public getServerInfo(options?: any) {
        return DiagnosticRoutesApiFp(this.configuration).getServerInfo(options)(this.axios, this.basePath);
    }

}
