// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';

import { NodeInfoDTO } from '../model';
import { NodeTimeDTO } from '../model';
/**
 * NodeRoutesApi - axios parameter creator
 * @export
 */
export const NodeRoutesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Supplies additional information about the application running on a node. 
         * @summary Get the node information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNodeInfo(options: any = {}): RequestArgs {
            const localVarPath = `/node/info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the node time at the moment the reply was sent and received.
         * @summary Get the node time
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNodeTime(options: any = {}): RequestArgs {
            const localVarPath = `/node/time`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NodeRoutesApi - functional programming interface
 * @export
 */
export const NodeRoutesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Supplies additional information about the application running on a node. 
         * @summary Get the node information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNodeInfo(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<NodeInfoDTO> {
            const localVarAxiosArgs = NodeRoutesApiAxiosParamCreator(configuration).getNodeInfo(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets the node time at the moment the reply was sent and received.
         * @summary Get the node time
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNodeTime(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<NodeTimeDTO> {
            const localVarAxiosArgs = NodeRoutesApiAxiosParamCreator(configuration).getNodeTime(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * NodeRoutesApi - factory interface
 * @export
 */
export const NodeRoutesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Supplies additional information about the application running on a node. 
         * @summary Get the node information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNodeInfo(options?: any) {
            return NodeRoutesApiFp(configuration).getNodeInfo(options)(axios, basePath);
        },
        /**
         * Gets the node time at the moment the reply was sent and received.
         * @summary Get the node time
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNodeTime(options?: any) {
            return NodeRoutesApiFp(configuration).getNodeTime(options)(axios, basePath);
        },
    };
};

/**
 * NodeRoutesApi - object-oriented interface
 * @export
 * @class NodeRoutesApi
 * @extends {BaseAPI}
 */
export class NodeRoutesApi extends BaseAPI {
    /**
     * Supplies additional information about the application running on a node. 
     * @summary Get the node information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NodeRoutesApi
     */
    public getNodeInfo(options?: any) {
        return NodeRoutesApiFp(this.configuration).getNodeInfo(options)(this.axios, this.basePath);
    }

    /**
     * Gets the node time at the moment the reply was sent and received.
     * @summary Get the node time
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NodeRoutesApi
     */
    public getNodeTime(options?: any) {
        return NodeRoutesApiFp(this.configuration).getNodeTime(options)(this.axios, this.basePath);
    }

}
